"""add paypal transactions table

Revision ID: 0a0c3c23dd59
Revises: 022c8388580c
Create Date: 2026-05-04 22:00:46.532558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0c3c23dd59'
down_revision: Union[str, Sequence[str], None] = '022c8388580c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paypal_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_payment_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('paypal_order_id', sa.String(length=100), nullable=False),
    sa.Column('paypal_status', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('installment', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_payment_id'], ['course_payments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paypal_transactions')
    # ### end Alembic commands ###
