"""add payment plan to course_payments

Revision ID: 420bff61d11f
Revises: 5d01d4c2de50
Create Date: 2026-04-12 02:18:27.153982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420bff61d11f'
down_revision: Union[str, Sequence[str], None] = '5d01d4c2de50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_payments', sa.Column('payment_plan', sa.String(length=20), nullable=True))
    op.add_column('course_payments', sa.Column('installment_1_paid', sa.Boolean(), nullable=True))
    op.add_column('course_payments', sa.Column('installment_2_paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_payments', 'installment_2_paid')
    op.drop_column('course_payments', 'installment_1_paid')
    op.drop_column('course_payments', 'payment_plan')
    # ### end Alembic commands ###
