"""sync_all_tables_with_models

Revision ID: f30932eeb474
Revises: 9fdb7437cc3b
Create Date: 2026-05-07 12:53:18.374749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f30932eeb474'
down_revision: Union[str, None] = '9fdb7437cc3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availability_slots', sa.Column('day_of_week', sa.SmallInteger(), nullable=False))
    op.alter_column('availability_slots', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('availability_slots', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.drop_column('availability_slots', 'weekday')
    op.add_column('blacklisted_tokens', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('blacklisted_tokens', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('blacklisted_tokens_jti_key'), 'blacklisted_tokens', type_='unique')
    op.drop_index(op.f('ix_blacklisted_tokens_jti'), table_name='blacklisted_tokens')
    op.drop_column('blacklisted_tokens', 'id')
    op.drop_column('blacklisted_tokens', 'blacklisted_at')
    op.add_column('course_payments', sa.Column('total_hours', sa.Integer(), nullable=False))
    op.add_column('course_payments', sa.Column('price_per_hour', sa.DECIMAL(precision=6, scale=2), nullable=False))
    op.add_column('course_payments', sa.Column('amount_paid', sa.DECIMAL(precision=8, scale=2), nullable=True))
    op.add_column('course_payments', sa.Column('amount_left', sa.DECIMAL(precision=8, scale=2), nullable=False))
    op.add_column('course_payments', sa.Column('no_refund', sa.Boolean(), nullable=True))
    op.add_column('course_payments', sa.Column('payment_plan', sa.String(length=20), nullable=True))
    op.add_column('course_payments', sa.Column('installment_1_paid', sa.Boolean(), nullable=True))
    op.add_column('course_payments', sa.Column('installment_2_paid', sa.Boolean(), nullable=True))
    op.alter_column('course_payments', 'language_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('course_payments', 'level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=3),
               nullable=False)
    op.alter_column('course_payments', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=8, scale=2),
               existing_nullable=False)
    op.alter_column('course_payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=True)
    op.alter_column('course_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('course_payments_teacher_id_fkey'), 'course_payments', type_='foreignkey')
    op.drop_constraint(op.f('course_payments_language_id_fkey'), 'course_payments', type_='foreignkey')
    op.drop_constraint(op.f('course_payments_student_id_fkey'), 'course_payments', type_='foreignkey')
    op.create_foreign_key(None, 'course_payments', 'teachers', ['teacher_id'], ['id'])
    op.create_foreign_key(None, 'course_payments', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'course_payments', 'languages', ['language_id'], ['id'])
    op.drop_column('course_payments', 'paid_at')
    op.drop_column('course_payments', 'teacher_amount')
    op.drop_column('course_payments', 'platform_fee')
    op.drop_column('course_payments', 'released_at')
    op.add_column('exam_answers', sa.Column('answer', sa.String(length=1), nullable=False))
    op.add_column('exam_answers', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('exam_answers_question_id_fkey'), 'exam_answers', type_='foreignkey')
    op.drop_constraint(op.f('exam_answers_attempt_id_fkey'), 'exam_answers', type_='foreignkey')
    op.create_foreign_key(None, 'exam_answers', 'exam_attempts', ['attempt_id'], ['id'])
    op.create_foreign_key(None, 'exam_answers', 'exam_questions', ['question_id'], ['id'])
    op.drop_column('exam_answers', 'answer_text')
    op.add_column('exam_attempts', sa.Column('teacher_id', sa.UUID(), nullable=False))
    op.add_column('exam_attempts', sa.Column('total', sa.Integer(), nullable=True))
    op.add_column('exam_attempts', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('exam_attempts_exam_id_fkey'), 'exam_attempts', type_='foreignkey')
    op.drop_constraint(op.f('exam_attempts_student_id_fkey'), 'exam_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'exam_attempts', 'exams', ['exam_id'], ['id'])
    op.create_foreign_key(None, 'exam_attempts', 'teachers', ['teacher_id'], ['id'])
    op.drop_column('exam_attempts', 'student_id')
    op.drop_column('exam_attempts', 'started_at')
    op.add_column('exam_questions', sa.Column('option_a', sa.String(length=200), nullable=False))
    op.add_column('exam_questions', sa.Column('option_b', sa.String(length=200), nullable=False))
    op.add_column('exam_questions', sa.Column('option_c', sa.String(length=200), nullable=False))
    op.add_column('exam_questions', sa.Column('option_d', sa.String(length=200), nullable=False))
    op.add_column('exam_questions', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('exam_questions', 'correct_answer',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1),
               existing_nullable=False)
    op.drop_constraint(op.f('exam_questions_exam_id_fkey'), 'exam_questions', type_='foreignkey')
    op.create_foreign_key(None, 'exam_questions', 'exams', ['exam_id'], ['id'])
    op.drop_column('exam_questions', 'question_type')
    op.drop_column('exam_questions', 'options')
    op.drop_column('exam_questions', 'order_index')
    op.drop_column('exam_questions', 'points')
    op.add_column('exams', sa.Column('created_by', sa.UUID(), nullable=False))
    op.alter_column('exams', 'level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=3),
               existing_nullable=False)
    op.alter_column('exams', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('exams', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('exams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('exams_language_id_fkey'), 'exams', type_='foreignkey')
    op.create_foreign_key(None, 'exams', 'languages', ['language_id'], ['id'])
    op.create_foreign_key(None, 'exams', 'teachers', ['created_by'], ['id'])
    op.drop_column('exams', 'description')
    op.drop_column('exams', 'pass_score')
    op.alter_column('languages', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.create_unique_constraint(None, 'languages', ['name'])
    op.drop_column('languages', 'is_active')
    op.add_column('lesson_materials', sa.Column('language_id', sa.Integer(), nullable=False))
    op.add_column('lesson_materials', sa.Column('level', sa.String(length=3), nullable=False))
    op.add_column('lesson_materials', sa.Column('type', sa.String(length=30), nullable=False))
    op.add_column('lesson_materials', sa.Column('file_path', sa.String(length=255), nullable=True))
    op.add_column('lesson_materials', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('lesson_materials', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('lesson_materials', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('lesson_materials_session_id_fkey'), 'lesson_materials', type_='foreignkey')
    op.drop_constraint(op.f('lesson_materials_teacher_id_fkey'), 'lesson_materials', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_materials', 'languages', ['language_id'], ['id'])
    op.create_foreign_key(None, 'lesson_materials', 'teachers', ['teacher_id'], ['id'])
    op.drop_column('lesson_materials', 'session_id')
    op.drop_column('lesson_materials', 'file_type')
    op.drop_column('lesson_materials', 'file_url')
    op.add_column('level_hours', sa.Column('hours_min', sa.Integer(), nullable=False))
    op.add_column('level_hours', sa.Column('hours_max', sa.Integer(), nullable=False))
    op.alter_column('level_hours', 'level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=3),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_level_hours_lang_level'), 'level_hours', type_='unique')
    op.drop_constraint(op.f('level_hours_language_id_fkey'), 'level_hours', type_='foreignkey')
    op.drop_column('level_hours', 'required_hours')
    op.drop_column('level_hours', 'language_id')
    op.drop_column('level_hours', 'id')
    op.add_column('level_pricing', sa.Column('price_min', sa.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('level_pricing', sa.Column('price_max', sa.DECIMAL(precision=5, scale=2), nullable=False))
    op.alter_column('level_pricing', 'level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=3),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_level_pricing_lang_level'), 'level_pricing', type_='unique')
    op.drop_constraint(op.f('level_pricing_language_id_fkey'), 'level_pricing', type_='foreignkey')
    op.drop_column('level_pricing', 'price_per_hour')
    op.drop_column('level_pricing', 'language_id')
    op.drop_column('level_pricing', 'id')
    op.add_column('messages', sa.Column('receiver_id', sa.UUID(), nullable=False))
    op.add_column('messages', sa.Column('liked', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.drop_index(op.f('ix_messages_recipient_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_constraint(op.f('messages_session_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_recipient_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'])
    op.drop_column('messages', 'session_id')
    op.drop_column('messages', 'sent_at')
    op.drop_column('messages', 'recipient_id')
    op.drop_column('messages', 'is_liked')
    op.add_column('payments', sa.Column('platform_fee', sa.DECIMAL(precision=8, scale=2), nullable=False))
    op.add_column('payments', sa.Column('teacher_payout', sa.DECIMAL(precision=8, scale=2), nullable=False))
    op.add_column('payments', sa.Column('both_reviewed', sa.Boolean(), nullable=True))
    op.add_column('payments', sa.Column('paid_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('payments', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('payments', 'course_payment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=8, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('payments_course_payment_id_fkey'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('payments_session_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'sessions', ['session_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'course_payments', ['course_payment_id'], ['id'])
    op.drop_column('payments', 'provider')
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'provider_ref')
    op.add_column('paypal_transactions', sa.Column('course_payment_id', sa.UUID(), nullable=False))
    op.add_column('paypal_transactions', sa.Column('student_id', sa.UUID(), nullable=False))
    op.add_column('paypal_transactions', sa.Column('paypal_status', sa.String(length=50), nullable=False))
    op.add_column('paypal_transactions', sa.Column('amount', sa.DECIMAL(precision=8, scale=2), nullable=False))
    op.add_column('paypal_transactions', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('paypal_transactions', sa.Column('installment', sa.Integer(), nullable=True))
    op.add_column('paypal_transactions', sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('paypal_transactions', 'paypal_order_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('paypal_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('paypal_transactions_payment_id_fkey'), 'paypal_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'paypal_transactions', 'course_payments', ['course_payment_id'], ['id'])
    op.create_foreign_key(None, 'paypal_transactions', 'students', ['student_id'], ['id'])
    op.drop_column('paypal_transactions', 'raw_response')
    op.drop_column('paypal_transactions', 'paypal_capture_id')
    op.drop_column('paypal_transactions', 'payment_id')
    op.drop_column('paypal_transactions', 'status')
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_column('refresh_tokens', 'revoked')
    op.add_column('reschedule_requests', sa.Column('new_time', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('reschedule_requests', sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('reschedule_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('reschedule_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('reschedule_requests_requested_by_fkey'), 'reschedule_requests', type_='foreignkey')
    op.create_foreign_key(None, 'reschedule_requests', 'users', ['requested_by'], ['id'])
    op.drop_column('reschedule_requests', 'new_scheduled_at')
    op.add_column('review_flags', sa.Column('flagged_user', sa.UUID(), nullable=False))
    op.add_column('review_flags', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('review_flags', sa.Column('reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('review_flags', 'reason',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('review_flags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('review_flags_flagged_by_fkey'), 'review_flags', type_='foreignkey')
    op.drop_constraint(op.f('review_flags_review_id_fkey'), 'review_flags', type_='foreignkey')
    op.create_foreign_key(None, 'review_flags', 'users', ['flagged_by'], ['id'])
    op.create_foreign_key(None, 'review_flags', 'users', ['flagged_user'], ['id'])
    op.drop_column('review_flags', 'review_id')
    op.add_column('reviews', sa.Column('written_by', sa.UUID(), nullable=False))
    op.add_column('reviews', sa.Column('role', sa.String(length=20), nullable=False))
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_review_session_student'), 'reviews', type_='unique')
    op.drop_constraint(op.f('reviews_session_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_student_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_teacher_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'sessions', ['session_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'users', ['written_by'], ['id'])
    op.create_foreign_key(None, 'reviews', 'teachers', ['teacher_id'], ['id'])
    op.drop_column('reviews', 'is_visible')
    op.add_column('session_attendance', sa.Column('student_id', sa.UUID(), nullable=False))
    op.add_column('session_attendance', sa.Column('was_present', sa.Boolean(), nullable=True))
    op.add_column('session_attendance', sa.Column('marked_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('session_attendance_session_id_fkey'), 'session_attendance', type_='foreignkey')
    op.drop_constraint(op.f('session_attendance_user_id_fkey'), 'session_attendance', type_='foreignkey')
    op.create_foreign_key(None, 'session_attendance', 'sessions', ['session_id'], ['id'])
    op.create_foreign_key(None, 'session_attendance', 'students', ['student_id'], ['id'])
    op.drop_column('session_attendance', 'user_id')
    op.drop_column('session_attendance', 'joined_at')
    op.drop_column('session_attendance', 'left_at')
    op.add_column('sessions', sa.Column('course_payment_id', sa.UUID(), nullable=False))
    op.add_column('sessions', sa.Column('videocall_url', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('rescheduled', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('teacher_review_done', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('student_review_done', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('payment_released', sa.Boolean(), nullable=True))
    op.alter_column('sessions', 'language_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=3),
               nullable=False)
    op.alter_column('sessions', 'duration_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sessions', 'daily_room_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('sessions', 'daily_room_url',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_sessions_scheduled_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_student_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_teacher_id'), table_name='sessions')
    op.drop_constraint(op.f('sessions_student_id_fkey'), 'sessions', type_='foreignkey')
    op.drop_constraint(op.f('sessions_teacher_id_fkey'), 'sessions', type_='foreignkey')
    op.drop_constraint(op.f('sessions_language_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'sessions', 'teachers', ['teacher_id'], ['id'])
    op.create_foreign_key(None, 'sessions', 'languages', ['language_id'], ['id'])
    op.create_foreign_key(None, 'sessions', 'course_payments', ['course_payment_id'], ['id'])
    op.drop_column('sessions', 'notes')
    op.drop_column('sessions', 'updated_at')
    op.add_column('student_languages', sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.execute("ALTER TABLE student_languages ALTER COLUMN id TYPE UUID USING (gen_random_uuid())")
    op.alter_column('student_languages', 'level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=3),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_student_language'), 'student_languages', type_='unique')
    op.drop_constraint(op.f('student_languages_language_id_fkey'), 'student_languages', type_='foreignkey')
    op.drop_constraint(op.f('student_languages_student_id_fkey'), 'student_languages', type_='foreignkey')
    op.create_foreign_key(None, 'student_languages', 'languages', ['language_id'], ['id'])
    op.create_foreign_key(None, 'student_languages', 'students', ['student_id'], ['id'])
    op.drop_column('student_languages', 'completed_hours')
    op.add_column('students', sa.Column('reschedule_count', sa.Integer(), nullable=True))
    op.alter_column('students', 'current_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=3),
               nullable=False)
    op.alter_column('students', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('students_user_id_key'), 'students', type_='unique')
    op.drop_constraint(op.f('students_target_language_id_fkey'), 'students', type_='foreignkey')
    op.drop_column('students', 'target_language_id')
    op.add_column('suspensions', sa.Column('teacher_id', sa.UUID(), nullable=True))
    op.add_column('suspensions', sa.Column('student_id', sa.UUID(), nullable=True))
    op.add_column('suspensions', sa.Column('role', sa.String(length=20), nullable=False))
    op.add_column('suspensions', sa.Column('no_refund', sa.Boolean(), nullable=True))
    op.add_column('suspensions', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('suspensions', sa.Column('suspended_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('suspensions', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('suspensions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.drop_constraint(op.f('suspensions_user_id_fkey'), 'suspensions', type_='foreignkey')
    op.drop_constraint(op.f('suspensions_suspended_by_fkey'), 'suspensions', type_='foreignkey')
    op.drop_constraint(op.f('suspensions_lifted_by_fkey'), 'suspensions', type_='foreignkey')
    op.create_foreign_key(None, 'suspensions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'suspensions', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'suspensions', 'teachers', ['teacher_id'], ['id'])
    op.drop_column('suspensions', 'suspended_by')
    op.drop_column('suspensions', 'lifted_by')
    op.drop_column('suspensions', 'starts_at')
    op.drop_column('suspensions', 'created_at')
    op.drop_column('suspensions', 'ends_at')
    op.add_column('teacher_certificates', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('teacher_certificates', sa.Column('file_path', sa.String(length=255), nullable=False))
    op.add_column('teacher_certificates', sa.Column('is_notarized', sa.Boolean(), nullable=True))
    op.add_column('teacher_certificates', sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('teacher_certificates', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.drop_constraint(op.f('teacher_certificates_language_id_fkey'), 'teacher_certificates', type_='foreignkey')
    op.drop_constraint(op.f('teacher_certificates_teacher_id_fkey'), 'teacher_certificates', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_certificates', 'teachers', ['teacher_id'], ['id'])
    op.drop_column('teacher_certificates', 'issue_date')
    op.drop_column('teacher_certificates', 'language_id')
    op.drop_column('teacher_certificates', 'created_at')
    op.drop_column('teacher_certificates', 'issuer')
    op.drop_column('teacher_certificates', 'title')
    op.drop_column('teacher_certificates', 'level')
    op.drop_column('teacher_certificates', 'file_url')
    op.add_column('teacher_noshow', sa.Column('notified', sa.Boolean(), nullable=True))
    op.add_column('teacher_noshow', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('teacher_noshow_session_id_fkey'), 'teacher_noshow', type_='foreignkey')
    op.drop_constraint(op.f('teacher_noshow_teacher_id_fkey'), 'teacher_noshow', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_noshow', 'sessions', ['session_id'], ['id'])
    op.create_foreign_key(None, 'teacher_noshow', 'teachers', ['teacher_id'], ['id'])
    op.drop_column('teacher_noshow', 'reported_at')
    op.add_column('teacher_verifications', sa.Column('verified_by', sa.UUID(), nullable=True))
    op.add_column('teacher_verifications', sa.Column('verification_type', sa.String(length=30), nullable=False))
    op.add_column('teacher_verifications', sa.Column('level_tested', sa.String(length=3), nullable=False))
    op.add_column('teacher_verifications', sa.Column('result', sa.String(length=20), nullable=False))
    op.add_column('teacher_verifications', sa.Column('tested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('teacher_verifications_reviewed_by_fkey'), 'teacher_verifications', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_verifications', 'teachers', ['verified_by'], ['id'])
    op.drop_column('teacher_verifications', 'reviewed_by')
    op.drop_column('teacher_verifications', 'created_at')
    op.drop_column('teacher_verifications', 'reviewed_at')
    op.drop_column('teacher_verifications', 'status')
    op.drop_column('teacher_verifications', 'document_url')
    op.add_column('teachers', sa.Column('language_id', sa.Integer(), nullable=False))
    op.add_column('teachers', sa.Column('is_native', sa.Boolean(), nullable=True))
    op.add_column('teachers', sa.Column('is_certified', sa.Boolean(), nullable=True))
    op.add_column('teachers', sa.Column('has_experience', sa.Boolean(), nullable=True))
    op.add_column('teachers', sa.Column('max_level', sa.String(length=3), nullable=False))
    op.add_column('teachers', sa.Column('passed_exam', sa.Boolean(), nullable=True))
    op.alter_column('teachers', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('teachers', 'hourly_rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('teachers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('teachers_user_id_key'), 'teachers', type_='unique')
    op.create_foreign_key(None, 'teachers', 'languages', ['language_id'], ['id'])
    op.drop_column('teachers', 'is_accepting_students')
    op.drop_column('teachers', 'languages_taught')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=60),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'google_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('users', 'is_suspended',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_google_id_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_google_id_key'), 'users', ['google_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('users', 'is_suspended',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('users', 'google_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=60),
               server_default=sa.text("'UTC'::character varying"),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               server_default=sa.text("'student'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.Text(),
               server_default=sa.text("''::character varying"),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=320),
               existing_nullable=False)
    op.add_column('teachers', sa.Column('languages_taught', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('teachers', sa.Column('is_accepting_students', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.create_unique_constraint(op.f('teachers_user_id_key'), 'teachers', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('teachers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('teachers', 'hourly_rate',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('teachers', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.drop_column('teachers', 'passed_exam')
    op.drop_column('teachers', 'max_level')
    op.drop_column('teachers', 'has_experience')
    op.drop_column('teachers', 'is_certified')
    op.drop_column('teachers', 'is_native')
    op.drop_column('teachers', 'language_id')
    op.add_column('teacher_verifications', sa.Column('document_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('teacher_verifications', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False))
    op.add_column('teacher_verifications', sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('teacher_verifications', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('teacher_verifications', sa.Column('reviewed_by', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'teacher_verifications', type_='foreignkey')
    op.create_foreign_key(op.f('teacher_verifications_reviewed_by_fkey'), 'teacher_verifications', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    op.drop_column('teacher_verifications', 'tested_at')
    op.drop_column('teacher_verifications', 'result')
    op.drop_column('teacher_verifications', 'level_tested')
    op.drop_column('teacher_verifications', 'verification_type')
    op.drop_column('teacher_verifications', 'verified_by')
    op.add_column('teacher_noshow', sa.Column('reported_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'teacher_noshow', type_='foreignkey')
    op.drop_constraint(None, 'teacher_noshow', type_='foreignkey')
    op.create_foreign_key(op.f('teacher_noshow_teacher_id_fkey'), 'teacher_noshow', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('teacher_noshow_session_id_fkey'), 'teacher_noshow', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('teacher_noshow', 'created_at')
    op.drop_column('teacher_noshow', 'notified')
    op.add_column('teacher_certificates', sa.Column('file_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('teacher_certificates', sa.Column('level', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('teacher_certificates', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('teacher_certificates', sa.Column('issuer', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('teacher_certificates', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('teacher_certificates', sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('teacher_certificates', sa.Column('issue_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'teacher_certificates', type_='foreignkey')
    op.create_foreign_key(op.f('teacher_certificates_teacher_id_fkey'), 'teacher_certificates', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('teacher_certificates_language_id_fkey'), 'teacher_certificates', 'languages', ['language_id'], ['id'], ondelete='SET NULL')
    op.alter_column('teacher_certificates', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.drop_column('teacher_certificates', 'uploaded_at')
    op.drop_column('teacher_certificates', 'is_notarized')
    op.drop_column('teacher_certificates', 'file_path')
    op.drop_column('teacher_certificates', 'name')
    op.add_column('suspensions', sa.Column('ends_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('suspensions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('suspensions', sa.Column('starts_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('suspensions', sa.Column('lifted_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('suspensions', sa.Column('suspended_by', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'suspensions', type_='foreignkey')
    op.drop_constraint(None, 'suspensions', type_='foreignkey')
    op.drop_constraint(None, 'suspensions', type_='foreignkey')
    op.create_foreign_key(op.f('suspensions_lifted_by_fkey'), 'suspensions', 'users', ['lifted_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('suspensions_suspended_by_fkey'), 'suspensions', 'users', ['suspended_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('suspensions_user_id_fkey'), 'suspensions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('suspensions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('suspensions', 'reason',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('suspensions', 'suspended_at')
    op.drop_column('suspensions', 'notes')
    op.drop_column('suspensions', 'no_refund')
    op.drop_column('suspensions', 'role')
    op.drop_column('suspensions', 'student_id')
    op.drop_column('suspensions', 'teacher_id')
    op.add_column('students', sa.Column('target_language_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('students_target_language_id_fkey'), 'students', 'languages', ['target_language_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('students_user_id_key'), 'students', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('students', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('students', 'current_level',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('students', 'reschedule_count')
    op.add_column('student_languages', sa.Column('completed_hours', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_languages', type_='foreignkey')
    op.drop_constraint(None, 'student_languages', type_='foreignkey')
    op.create_foreign_key(op.f('student_languages_student_id_fkey'), 'student_languages', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('student_languages_language_id_fkey'), 'student_languages', 'languages', ['language_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_student_language'), 'student_languages', ['student_id', 'language_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('student_languages', 'level',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('student_languages', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('student_languages', 'started_at')
    op.add_column('sessions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_language_id_fkey'), 'sessions', 'languages', ['language_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('sessions_teacher_id_fkey'), 'sessions', 'teachers', ['teacher_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('sessions_student_id_fkey'), 'sessions', 'students', ['student_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_sessions_teacher_id'), 'sessions', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_sessions_student_id'), 'sessions', ['student_id'], unique=False)
    op.create_index(op.f('ix_sessions_scheduled_at'), 'sessions', ['scheduled_at'], unique=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'daily_room_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('sessions', 'daily_room_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('sessions', 'duration_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('60'),
               existing_nullable=False)
    op.alter_column('sessions', 'level',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('sessions', 'language_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('sessions', 'payment_released')
    op.drop_column('sessions', 'student_review_done')
    op.drop_column('sessions', 'teacher_review_done')
    op.drop_column('sessions', 'rescheduled')
    op.drop_column('sessions', 'videocall_url')
    op.drop_column('sessions', 'course_payment_id')
    op.add_column('session_attendance', sa.Column('left_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('session_attendance', sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('session_attendance', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'session_attendance', type_='foreignkey')
    op.drop_constraint(None, 'session_attendance', type_='foreignkey')
    op.create_foreign_key(op.f('session_attendance_user_id_fkey'), 'session_attendance', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('session_attendance_session_id_fkey'), 'session_attendance', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('session_attendance', 'marked_at')
    op.drop_column('session_attendance', 'was_present')
    op.drop_column('session_attendance', 'student_id')
    op.add_column('reviews', sa.Column('is_visible', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_teacher_id_fkey'), 'reviews', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('reviews_student_id_fkey'), 'reviews', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('reviews_session_id_fkey'), 'reviews', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_review_session_student'), 'reviews', ['session_id', 'student_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reviews', 'rating',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('reviews', 'role')
    op.drop_column('reviews', 'written_by')
    op.add_column('review_flags', sa.Column('review_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'review_flags', type_='foreignkey')
    op.drop_constraint(None, 'review_flags', type_='foreignkey')
    op.create_foreign_key(op.f('review_flags_review_id_fkey'), 'review_flags', 'reviews', ['review_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('review_flags_flagged_by_fkey'), 'review_flags', 'users', ['flagged_by'], ['id'], ondelete='CASCADE')
    op.alter_column('review_flags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('review_flags', 'reason',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('review_flags', 'reviewed_at')
    op.drop_column('review_flags', 'status')
    op.drop_column('review_flags', 'flagged_user')
    op.add_column('reschedule_requests', sa.Column('new_scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reschedule_requests', type_='foreignkey')
    op.create_foreign_key(op.f('reschedule_requests_requested_by_fkey'), 'reschedule_requests', 'users', ['requested_by'], ['id'], ondelete='CASCADE')
    op.alter_column('reschedule_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reschedule_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.drop_column('reschedule_requests', 'resolved_at')
    op.drop_column('reschedule_requests', 'new_time')
    op.add_column('refresh_tokens', sa.Column('revoked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.add_column('paypal_transactions', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('paypal_transactions', sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('paypal_transactions', sa.Column('paypal_capture_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('paypal_transactions', sa.Column('raw_response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'paypal_transactions', type_='foreignkey')
    op.drop_constraint(None, 'paypal_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('paypal_transactions_payment_id_fkey'), 'paypal_transactions', 'payments', ['payment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('paypal_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('paypal_transactions', 'paypal_order_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('paypal_transactions', 'completed_at')
    op.drop_column('paypal_transactions', 'installment')
    op.drop_column('paypal_transactions', 'currency')
    op.drop_column('paypal_transactions', 'amount')
    op.drop_column('paypal_transactions', 'paypal_status')
    op.drop_column('paypal_transactions', 'student_id')
    op.drop_column('paypal_transactions', 'course_payment_id')
    op.add_column('payments', sa.Column('provider_ref', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_session_id_fkey'), 'payments', 'sessions', ['session_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('payments_course_payment_id_fkey'), 'payments', 'course_payments', ['course_payment_id'], ['id'], ondelete='SET NULL')
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.DECIMAL(precision=8, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'course_payment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('payments', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('payments', 'paid_at')
    op.drop_column('payments', 'both_reviewed')
    op.drop_column('payments', 'teacher_payout')
    op.drop_column('payments', 'platform_fee')
    op.add_column('messages', sa.Column('is_liked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('recipient_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_recipient_id_fkey'), 'messages', 'users', ['recipient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('messages_session_id_fkey'), 'messages', 'sessions', ['session_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_recipient_id'), 'messages', ['recipient_id'], unique=False)
    op.alter_column('messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'liked')
    op.drop_column('messages', 'receiver_id')
    op.add_column('level_pricing', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('level_pricing', sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('level_pricing', sa.Column('price_per_hour', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('level_pricing_language_id_fkey'), 'level_pricing', 'languages', ['language_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_level_pricing_lang_level'), 'level_pricing', ['language_id', 'level'], postgresql_nulls_not_distinct=False)
    op.alter_column('level_pricing', 'level',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('level_pricing', 'price_max')
    op.drop_column('level_pricing', 'price_min')
    op.add_column('level_hours', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('level_hours', sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('level_hours', sa.Column('required_hours', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('level_hours_language_id_fkey'), 'level_hours', 'languages', ['language_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_level_hours_lang_level'), 'level_hours', ['language_id', 'level'], postgresql_nulls_not_distinct=False)
    op.alter_column('level_hours', 'level',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('level_hours', 'hours_max')
    op.drop_column('level_hours', 'hours_min')
    op.add_column('lesson_materials', sa.Column('file_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('lesson_materials', sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('lesson_materials', sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lesson_materials', type_='foreignkey')
    op.drop_constraint(None, 'lesson_materials', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_materials_teacher_id_fkey'), 'lesson_materials', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('lesson_materials_session_id_fkey'), 'lesson_materials', 'sessions', ['session_id'], ['id'], ondelete='SET NULL')
    op.alter_column('lesson_materials', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lesson_materials', 'title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('lesson_materials', 'description')
    op.drop_column('lesson_materials', 'file_path')
    op.drop_column('lesson_materials', 'type')
    op.drop_column('lesson_materials', 'level')
    op.drop_column('lesson_materials', 'language_id')
    op.add_column('languages', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'languages', type_='unique')
    op.alter_column('languages', 'name',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('exams', sa.Column('pass_score', sa.INTEGER(), server_default=sa.text('70'), autoincrement=False, nullable=False))
    op.add_column('exams', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.create_foreign_key(op.f('exams_language_id_fkey'), 'exams', 'languages', ['language_id'], ['id'], ondelete='CASCADE')
    op.alter_column('exams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('exams', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('exams', 'title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('exams', 'level',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('exams', 'created_by')
    op.add_column('exam_questions', sa.Column('points', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('exam_questions', sa.Column('order_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('exam_questions', sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('exam_questions', sa.Column('question_type', sa.VARCHAR(length=20), server_default=sa.text("'multiple_choice'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exam_questions', type_='foreignkey')
    op.create_foreign_key(op.f('exam_questions_exam_id_fkey'), 'exam_questions', 'exams', ['exam_id'], ['id'], ondelete='CASCADE')
    op.alter_column('exam_questions', 'correct_answer',
               existing_type=sa.String(length=1),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('exam_questions', 'created_at')
    op.drop_column('exam_questions', 'option_d')
    op.drop_column('exam_questions', 'option_c')
    op.drop_column('exam_questions', 'option_b')
    op.drop_column('exam_questions', 'option_a')
    op.add_column('exam_attempts', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('exam_attempts', sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exam_attempts', type_='foreignkey')
    op.drop_constraint(None, 'exam_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('exam_attempts_student_id_fkey'), 'exam_attempts', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('exam_attempts_exam_id_fkey'), 'exam_attempts', 'exams', ['exam_id'], ['id'], ondelete='CASCADE')
    op.drop_column('exam_attempts', 'created_at')
    op.drop_column('exam_attempts', 'total')
    op.drop_column('exam_attempts', 'teacher_id')
    op.add_column('exam_answers', sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exam_answers', type_='foreignkey')
    op.drop_constraint(None, 'exam_answers', type_='foreignkey')
    op.create_foreign_key(op.f('exam_answers_attempt_id_fkey'), 'exam_answers', 'exam_attempts', ['attempt_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('exam_answers_question_id_fkey'), 'exam_answers', 'exam_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_column('exam_answers', 'created_at')
    op.drop_column('exam_answers', 'answer')
    op.add_column('course_payments', sa.Column('released_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('course_payments', sa.Column('platform_fee', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('course_payments', sa.Column('teacher_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('course_payments', sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'course_payments', type_='foreignkey')
    op.drop_constraint(None, 'course_payments', type_='foreignkey')
    op.drop_constraint(None, 'course_payments', type_='foreignkey')
    op.create_foreign_key(op.f('course_payments_student_id_fkey'), 'course_payments', 'students', ['student_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('course_payments_language_id_fkey'), 'course_payments', 'languages', ['language_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('course_payments_teacher_id_fkey'), 'course_payments', 'teachers', ['teacher_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('course_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('course_payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               nullable=False)
    op.alter_column('course_payments', 'total_amount',
               existing_type=sa.DECIMAL(precision=8, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('course_payments', 'level',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('course_payments', 'language_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('course_payments', 'installment_2_paid')
    op.drop_column('course_payments', 'installment_1_paid')
    op.drop_column('course_payments', 'payment_plan')
    op.drop_column('course_payments', 'no_refund')
    op.drop_column('course_payments', 'amount_left')
    op.drop_column('course_payments', 'amount_paid')
    op.drop_column('course_payments', 'price_per_hour')
    op.drop_column('course_payments', 'total_hours')
    op.add_column('blacklisted_tokens', sa.Column('blacklisted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('blacklisted_tokens', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_blacklisted_tokens_jti'), 'blacklisted_tokens', ['jti'], unique=False)
    op.create_unique_constraint(op.f('blacklisted_tokens_jti_key'), 'blacklisted_tokens', ['jti'], postgresql_nulls_not_distinct=False)
    op.drop_column('blacklisted_tokens', 'created_at')
    op.drop_column('blacklisted_tokens', 'expires_at')
    op.add_column('availability_slots', sa.Column('weekday', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('availability_slots', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('availability_slots', 'timezone',
               existing_type=sa.String(length=60),
               server_default=sa.text("'UTC'::character varying"),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('availability_slots', 'day_of_week')
    # ### end Alembic commands ###
